export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}>
         
            <p>Header</p>
         
        </header>

        {children}

        <footer  style={{
         backgroundColor: "gray",
         padding: "1rem",
        }}>
        <p>Footer</p>      
        </footer>

      </body>
    </html>
  );
}
